-- Add detailed token and cost tracking to messages table
-- This allows tracking AI costs per message and per contact conversation

ALTER TABLE messages
ADD COLUMN IF NOT EXISTS input_tokens integer,
ADD COLUMN IF NOT EXISTS output_tokens integer,
ADD COLUMN IF NOT EXISTS ai_model text,
ADD COLUMN IF NOT EXISTS ai_cost numeric(10, 6);

-- Add comment explaining the fields
COMMENT ON COLUMN messages.input_tokens IS 'Number of input tokens sent to the AI model';
COMMENT ON COLUMN messages.output_tokens IS 'Number of output tokens generated by the AI model';
COMMENT ON COLUMN messages.ai_model IS 'The AI model used to generate the response (e.g., claude-opus-4-5-20251101)';
COMMENT ON COLUMN messages.ai_cost IS 'Cost in USD for this AI generation';
